## These functions allow the user to make a matrix 
##      whose inverse can be calculuated and cached for later use.

## makeCacheMatrix, creates a 'matrix'-like object with the 
##      ability to cache its inverse once computed.

makeCacheMatrix <- function(X = matrix()) {
        inv <- NULL   # The inverse is not computed at first.
        
        # This sets the value of the input matrix.
        set <- function(Y) {
                X <<- Y
                inv <<- NULL
        }
        
        # This reports the value of the input matrix.
        get <- function() X
        
        # This accepts an inverse and sets it to 'inv'.
        setinv <- function(inverse) inv <<- inverse
        
        # This reports 'inv'.
        getinv <- function() inv
        
        # This a list of accessible functions.
        list(set = set, get = get, 
             setinv = setinv,
             getinv = getinv)
}


## cacheSolve, works with the 'matrix'-like object
##      generated by makeCacheMatrix to both compute the inverse and 
##      access the cached version once the inverse has been computed.

cacheSolve <- function(X) {
        inv <- X$getinv()    # Run the 'getinv' function from X
        if(!is.null(inv)) {  # If inv has been previously set, don't recalculate
                message("getting cached data")
                return(inv)
        }
        M <- X$get()  # Run the 'get' function from X
        inv <- solve(M)
        X$setinv(inv)
        inv
}
